keycloakx:
  replicas: 1

  proxy:
    mode: xforwarded

  args:
    - start

  image:
    registry: quay.io
    repository: keycloak/keycloak
    tag: 26.5.6

  database:
    vendor: postgres
    hostname: keycloak-db-rw.postgres.svc
    port: 5432
    database: keycloak
    username: keycloak
    existingSecret: keycloak-db-keycloak
    existingSecretPasswordKey: password

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

  extraEnv: |
    - name: KC_PROXY_HEADERS
      value: xforwarded
    - name: KC_HOSTNAME
      value: "https://your-keycloak.domain.com"
    - name: KC_HOSTNAME_STRICT
      value: "false"
    - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
      value: "true"
    - name: KC_HTTP_ENABLED
      value: "true"
    - name: KC_HTTP_PORT
      value: "8080"
    - name: KC_BOOTSTRAP_ADMIN_USERNAME
      value: admin
    - name: KC_BOOTSTRAP_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-admin
          key: password

  service:
    type: ClusterIP

  ingress:
    enabled: false
