apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: {{ .Values.config.storage.delete.enabled }}
    http:
      addr: :5000
      debug:
        addr: :5001
        enabled: {{ .Values.config.http.debug.enabled }}
    {{- if .Values.proxy.remoteUrl }}
    proxy:
      remoteurl: {{ .Values.proxy.remoteUrl }}
    {{- end }}
    {{- if .Values.config.middleware }}
    middleware:
      {{- toYaml .Values.config.middleware | nindent 6 }}
    {{- end }}
