{{- if .Values.proxy.existingSecret.name }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.proxy.existingSecret.name }}
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.proxy.existingSecret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: {{ .Values.proxy.existingSecret.usernameKey }}
      remoteRef:
        key: secrets/data/dockerhub
        property: user
    - secretKey: {{ .Values.proxy.existingSecret.passwordKey }}
      remoteRef:
        key: secrets/data/dockerhub
        property: password
{{- end }}
