minio:
  extraEnvVars:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: https://artis-dev.fronius.com/minio/
    - name: MINIO_CONSOLE_SUBPATH
      value: /minio
    - name: MINIO_BROWSER
      value: "on"
    # - name: MINIO_SERVER_URL
    #   value: minio.argo.svc.cluster.local:9000
  tls:
    enabled: false

  auth:
    ## @param auth.rootUser MinIO&reg; root username
    ##
    rootUser: artis
    ## @param auth.rootPassword Password for MinIO&reg; root user
    ##
    rootPassword: "artisRules"

  defaultBuckets: "argo-storage, thanos-store"
  
  provisioning:
    enabled: true
    buckets:
      - name: argo-storage
        lifecycle:
          - id: retention
            prefix: ret
            disabled: false
            expiry:
              days: 7
 
  service:
    ## @param service.type MinIO&reg; service type
    ##
    type: LoadBalancer
  
  persistence:
    mountPath: /data
    size: 40Gi
    accessModes:
      - ReadWriteOnce
    existingClaim: pvc-qumulo-minio
  
  image:
    debug: true

  volumePermissions:
    enabled: false
  
  # ingress:
  #   enabled: true
  #   ingressClassName: nginx
  #   hostname: artis-dev.fronius.com
  #   path: /minio

  # apiIngress:
  #   enabled: true
  #   ingressClassName: nginx
  #   hostname: artis-dev.fronius.com
  #   path: /minio