apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-auth-secret
  namespace: backstage
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: backstage-auth-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: session-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/data/backstage
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: session-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-backstage
  namespace: backstage
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: backstage-keycloak-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/data/keycloak-backstage-client
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: client-secret
