apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: boston-training-
spec:
  serviceAccount: argo
  entrypoint: boston
  templates:
  - name: boston
    container:
      image: ortegatrom/iris-mlflow 
      