apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  name: boston-training
spec:
  serviceAccount: argo
  entrypoint: boston
  templates:
  - name: boston
    container:
      image: ortegatrom/boston-mlflow 
      