apiVersion: v2
name: argo-workflows
description: A Helm chart for self-manging argo-workflows
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: argo-workflows
  version: 0.40.10
  repository: https://argoproj.github.io/argo-helm
