apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ngrok-operator
    repo: https://charts.ngrok.com
    version: 0.18.1
    releaseName: ngrok-operator
    valuesFile: values.yaml

resources:
  - ngrok-secret.yamls
