apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: NgrokTrafficPolicy
metadata:
  name: shared-traffic-policy
  namespace: argocd
spec:
  policy:
    on_http_request:
      - name: Initialize-Local-Service-Match
        actions:
          - type: set-vars
            config:
              vars:
                - request_matched_local_svc: false

      - name: Generated-Local-Service-Route
        expressions:
          - "req.url.path.startsWith('/')"
          - "vars.request_matched_local_svc == false"
        actions:
          - type: set-vars
            config:
              vars:
                - request_matched_local_svc: true

      - name: Fallback-404
        expressions:
          - "vars.request_matched_local_svc == false"
        actions:
          - type: custom-response
            config:
              status_code: 404
              headers:
                content-type: text/plain
              content: "No route was found for this ngrok Endpoint"
