apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: TrafficPolicy
metadata:
  name: shared-traffic-policy
  namespace: ngrok
spec:
  # A minimal traffic policy that mirrors the operator's generated default
  # structure. The operator expects all Ingresses sharing a hostname to
  # reference the same traffic policy and pooling-enabled configuration.
  onHttpRequest:
    - name: Initialize-Local-Service-Match
      actions:
        - type: set-vars
          config:
            vars:
              - name: request_matched_local_svc
                value: false

    - name: Generated-Local-Service-Route
      expressions:
        - "req.url.path.startsWith('/')"
        - "vars.request_matched_local_svc == false"
      actions:
        - type: set-vars
          config:
            vars:
              - name: request_matched_local_svc
                value: true

    - name: Fallback-404
      expressions:
        - "vars.request_matched_local_svc == false"
      actions:
        - type: custom-response
          config:
            status_code: 404
            headers:
              content-type: text/plain
            content: "No route was found for this ngrok Endpoint"
