apiVersion: v2
name: gatekeeper
version: v1
description: Helm chart to deploy gatekeeper
dependencies:
  - name: gatekeeper
    version: 3.18.2
    repository: https://open-policy-agent.github.io/gatekeeper/charts
maintainers: 
  - name: Andres Ortega
    email: afortegast@gmail.com
    url: https://www.linkedin.com/in/andres-ortega-97435535/