# Using chart defaults for 'postgresql-ha' images.
# Removed custom image overrides because the referenced repositories/tags
# are no longer available on Docker Hub and caused ImagePullBackOff.
#
# To provide custom images, uncomment and set verified repository/tag values,
# for example:
# postgresql-ha:
#   postgresql:
#     image:
#       registry: docker.io
#       repository: myregistry/postgresql-repmgr
#       tag: 14.7.0-debian-11-r17
#   pgpool:
#     image:
#       registry: docker.io
#       repository: myregistry/pgpool
#       tag: 4.4.2-debian-11-r20
#   volumePermissions:
#     image:
#       registry: docker.io
#       repository: myregistry/bitnami-shell
#       tag: 11-debian-11-r0

# Quick fix: override only the init/volume-permissions image with a small
# widely-available image so the init containers can run while you decide
# how to handle the Bitnami images for pgpool/postgresql (they appear to
# be removed or have moved from Docker Hub).
postgresql-ha:
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: alpine
      tag: 3.18
    podSecurityContext:
      runAsUser: 0