apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: argocd-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        clientSecret: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: secrets/data/argocd
        property: oidc-secret
