apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: argocd-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: clientSecret
      remoteRef:
        key: secrets/data/argocd
        property: oidc-secret
