apiVersion: v2
name: istiod
version: "1"
description: Helm chart to deploy Istio control plane
dependencies:
  - name: istiod
    version: 1.29.1
    repository: https://istio-release.storage.googleapis.com/charts
maintainers:
  - name: Andres Ortega
    email: afortegast@gmail.com
    url: https://www.linkedin.com/in/andres-ortega-97435535/
