apiVersion: v2
name: postgresql
description: A Helm chart for postgresql
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: postgresql
  version: 12.4.3
  repository: "https://charts.bitnami.com/bitnami"
