apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.5.2
      helm:
        valueFiles:
          - $values/argocd/values.yaml
    - repoURL: https://github.com/afos2000/stack.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/afos2000/stack.git
      targetRevision: HEAD
      path: argocd/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
