apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.0.4
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    valuesFile: values.yaml


