nameOverride: argocd
fullnameOverride: "argocd"

global:
  domain: argocd.andreskube.uk

crds:
  install: false
  keep: true

configs:
  cm:
    admin.enabled: true
    timeout.reconciliation: 180s
    url: https://argocd.andreskube.uk
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.andreskube.uk/realms/argocd
      clientID: argocd
      clientSecret: $argocd-oidc-secret:clientSecret
      requestedScopes:
        - openid
        - profile
        - email
    ui.bannercontent: |
      Want access? Open a PR at https://github.com/afos2000/argocd-homelab-access
    ui.bannerurl: https://github.com/afos2000/argocd-homelab-access
  rbac:
    create: false

dex:
  enabled: false
