apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-backstage-client
  namespace: keycloak
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: keycloak-backstage-client
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/data/keycloak-backstage-client
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: client-secret
