apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-argocd
  labels:
    app: keycloak
data:
  realm-argocd.json: |
    {
      "realm": "argocd",
      "enabled": true,
      "displayName": "ArgoCD",
      "clients": [
        {
          "clientId": "argocd",
          "enabled": true,
          "protocol": "openid-connect",
          "clientAuthenticatorType": "client-secret",
          "standardFlowEnabled": true,
          "redirectUris": [
            "https://argocd.andreskube.uk/auth/callback"
          ],
          "webOrigins": ["+"],
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "config": {
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "groups",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "argocd-admin"
          },
          {
            "name": "argocd-readonly"
          }
        ]
      }
    }
