apiVersion: v2
name: metallb
version: v1
description: Helm chart to deploy metallb
dependencies:
  - name: metallb
    version: 0.15.3
    repository: https://metallb.github.io/metallb
maintainers: 
  - name: Andres Ortega
    email: afortegast@gmail.com
    url: https://www.linkedin.com/in/andres-ortega-97435535/
