minio:
  tls:
    enabled: false

  auth:
    ## @param auth.rootUser MinIO&reg; root username
    ##
    rootUser: andres
    ## @param auth.rootPassword Password for MinIO&reg; root user
    ##
    rootPassword: "andresRules"

  defaultBuckets: "argo-storage"



  
