apiVersion: v2
name: longhorn
version: "1"
description: Helm chart to deploy Longhorn
dependencies:
  - name: longhorn
    version: 1.7.2
    repository: https://charts.longhorn.io
maintainers:
  - name: Andres Ortega
    email: afortegast@gmail.com
    url: https://www.linkedin.com/in/andres-ortega-97435535/
