apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 
      revision: HEAD
      directories:
      - path: 'cluster-apps/**/dev'
      - path: cluster-apps/argo/*
        exclude: true

  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: cluster-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: 
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
