apiVersion: v2
name: cert-manager
version: v1
description: Helm chart to deploy cert-manager
dependencies:
  - name: cert-manager
    version: 1.17.2
    repository: https://charts.jetstack.io
maintainers: 
  - name: Andres Ortega
    email: afortegast@gmail.com
    url: https://www.linkedin.com/in/andres-ortega-97435535/